<?php
$options="";
$dato = utf8_decode($_POST['elegido']);

if ($_POST["elegido"]=="Amazonas") {
    $options= '
    <option value="Leticia"> Leticia </option>
    <option value="El Encanto"> El Encanto </option>
    <option value="La Chorrera"> La Chorrera </option>
    <option value="La Pedrera"> La Pedrera </option>
    <option value="La Victoria"> La Victoria </option>
    <option value="Miriti - Parana"> Miriti - Parana </option>
    <option value="Puerto Alegria"> Puerto Alegria </option>
    <option value="Puerto Arica "> Puerto Arica </option>
    <option value="Puerto Nariño"> Puerto Nariño </option>
    <option value="Puerto Santander"> Puerto Santander </option>
    <option value="Tarapaca"> Tarapaca </option>
    ';
}
if ($_POST["elegido"]=="Antioquia") {
    $options= '
    <option value="Medellin"> Medellin </option>
    <option value="Abejorral"> Abejorral </option>
    <option value="Abriaqui"> Abriaqui </option>
    <option value="Alejandria"> Alejandria </option>
    <option value="Amaga"> Amaga </option>
    <option value="Amalfi"> Amalfi </option>
    <option value="Andes"> Andes </option>
    <option value="Angelopólis"> Angelopólis </option>
    <option value="Angostura"> Angostura </option>
    <option value="Anori"> Anori </option>
    <option value="Anza"> Anza </option>
    <option value="Apartado"> Apartado </option>
    <option value="Arboletes"> Arboletes </option>
    <option value="Armenia"> Armenia </option>
    <option value="Barbosa"> Barbosa </option>
    <option value="Bello"> Bello </option>
    <option value="Belmira"> Belmira </option>
    <option value="Betania"> Betania </option>
    <option value="Betulia"> Betulia </option>
    <option value="Briceño"> Briceño </option>
    <option value="Buritica"> Buritica </option>
    <option value="Caceres"> Caceres </option>
    <option value="Caicedo"> Caicedo </option>
    <option value="Caldas"> Caldas </option>
    <option value="Campamento"> Campamento </option>
    <option value="CañasGordas"> CañasGordas </option>
    <option value="Caracoli"> Caracoli </option>
    <option value="Caramanta"> Caramanta </option>
    <option value="Carepa"> Carepa </option>
    <option value="Carolina"> Carolina </option>
    <option value="Caucacia"> Caucacia </option>
    <option value="Chigorodo"> Chigorodo </option>
    <option value="Cisneros"> Cisneros </option>
    <option value="Ciudad Bolivar"> Ciudad Bolivar </option>
    <option value="Cocorna"> Cocorna </option>
    <option value="Concepción"> Concepción </option>
    <option value="Concordia"> Concordia </option>
    <option value="Copacabana"> Copacabana </option>
    <option value="Debaiba"> Debaiba </option>
    <option value="Don Matias"> Don Matias </option>
    <option value="Ebejico"> Ebejico </option>
    <option value="El Bagre"> El Bagre </option>
    <option value="El Carmen de Viboral"> El Carmen de Viboral </option>
    <option value="El Santuario"> El Santuario </option>
    <option value="Entrerrios"> Entrerrios </option>
    <option value="Envigado"> Envigado </option>
    <option value="Fredonia"> Fredonia </option>
    <option value="Frontino"> Frontino </option>
    <option value="Giraldo"> Giraldo </option>
    <option value="Girardota"> Girardota </option>
    <option value="Gomez Plata"> Gomez Plata </option>
    <option value="Granada"> Granada </option>
    <option value="Granada"> Guadalupe </option>
    <option value="Guarne"> Guarne </option>
    <option value="Guatape"> Guatape </option>
    <option value="Heliconia"> Heliconia </option>
    <option value="Hispania"> Hispania </option>
    <option value="Itagui"> Itagui </option>
    <option value="Ituango"> Ituango </option>
    <option value="Jardin"> Jardin </option>
    <option value="Jerico"> Jerico </option>
    <option value="La Ceja"> La Ceja </option>
    <option value="La Estrella"> La Estrella </option>
    <option value="La Pintada"> La Pintada </option>
    <option value="La Union"> La Union </option>
    <option value="Liborina"> Liborina </option>
    <option value="Maceo"> Maceo </option>
    <option value="Marinilla"> Marinilla </option>
    <option value="Montebello"> Montebello </option>
    <option value="Murindo"> Murindo </option>
    <option value="Mutata"> Mutata </option>
    <option value="Nariño"> Nariño </option>
    <option value="Nechi"> Nechi </option>
    <option value="Necocli"> Necocli </option>
    <option value="Olaya"> Olaya </option>
    <option value="Pedol"> Pedol </option>
    <option value="Pequea"> Pequea </option>
    <option value="Pueblorrico Pueblorrico </option>
    <option value="Puerto Berrio"> Puerto Berrio </option>
    <option value="Puerto Nare"> Puerto Nare </option>
    <option value="Puerto Triunfo"> Puerto Triunfo </option>
    <option value="Remedios"> Remedios </option>
    <option value="Retiro"> Retiro </option>
    <option value="Rionegro"> Rionegro </option>
    <option value="Sabanalarga"> Sabanalarga </option>
    <option value="Sabaneta"> Sabaneta </option>
    <option value="Salgar"> Salgar </option>
    <option value="San Andres de Cuerquia"> San Andres de Cuerquia </option>
    <option value="San Carlos"> San Carlos </option>
    <option value="San Francisco"> San Francisco </option>
    <option value="San Jeronimo"> San Jeronimo </option>
    <option value="San Jose de la Montaña"> San Jose de la Montaña </option>
    <option value="San Juan de Uraba"> San Juan de Uraba </option>
    <option value="San Luis"> San Luis </option>
    <option value="San Pedro"> San Pedro </option>
    <option value="San Pedro de Uraba"> San Pedro de Uraba </option>
    <option value="San Rafael"> San Rafael </option>
    <option value="San Roque"> San Roque </option>
    <option value="San Vicente"> San Vicente </option>
    <option value="Santa Barbara"> Santa Barbara </option>
    <option value="Santa Rosa de Osos"> Santa Rosa de Osos </option>
    <option value="SantaFe de Antioquia"> SantaFe de Antioquia </option>
    <option value="Santo Domingo"> Santo Domingo </option>
    <option value="Segovia"> Segovia </option>
    <option value="Sonson"> Sonson </option>
    <option value="Sopetran"> Sopetran </option>
    <option value="Tamesis"> Tamesis </option>
    <option value="Taraza"> Taraza </option>
    <option value="Tarso"> Tarso </option>
    <option value="Titiribi"> Titiribi </option>
    <option value="Toledo"> Toledo </option>
    <option value="Turbo"> Turbo </option>
    <option value="Uramita"> Uramita </option>
    <option value="Urrao"> Urrao </option>
    <option value="Valdivia"> Valdivia </option>
    <option value="Valparaiso"> Valparaiso </option>
    <option value="Vagachi"> Vagachi </option>
    <option value="Venecia"> Venecia </option>
    <option value="Vigia del Fuerte"> Vigia del Fuerte </option>
    <option value="Yali"> Yali </option>
    <option value="Yarumal"> Yarumal </option>
    <option value="Yolondo"> Yolondo </option>
    <option value="Yondo"> Yondo </option>
    <option value="Zaragoza"> Zaragoza </option>
    ';
}
if ($_POST["elegido"]=="Arauca") {
    $options= '
    <option value="Arauca"> Arauca </option>
    <option value="Arauquita"> Arauquita </option>
    <option value="Cravo Norte"> Cravo Norte </option>
    <option value="Fortul"> Fortul </option>
    <option value="Puerto Rondon"> Puerto Rondon </option>
    <option value="Saravena"> Saravena </option>
    <option value="Tame"> Tame </option>
    ';
}
if ($_POST["elegido"]=="Atlántico") {
    $options= '
    <option value="Barranquilla"> Barranquilla </option>
    <option value="Baranoa"> Baranoa </option>
    <option value="Campo de la Cruz"> Campo de la Cruz </option>
    <option value="Candelaria"> Candelaria </option>
    <option value="Galapa"> Galapa </option>
    <option value="Juan de Acosta"> Juan de Acosta </option>
    <option value="Luruaco"> Luruaco </option>
    <option value="Malambo"> Malambo </option>
    <option value="Manati"> Manati </option>
    <option value="Palmar de Varela"> Palmar de Varela </option>
    <option value="Piojo"> Piojo </option>
    <option value="Palonuevo"> Palonuevo </option>
    <option value="Ponedera"> Ponedera </option>
    <option value="Puerto Colombia"> Puerto Colombia </option>
    <option value="Repelon"> Repelon </option>
    <option value="Repelon"> Sabanagrande </option>
    <option value="Sabanalarga"> Sabanalarga </option>
    <option value="Santa Lucia"> Santa Lucia </option>
    <option value="Santo Tomas"> Santo Tomas </option>
    <option value="Soledad"> Soledad </option>
    <option value="Suan"> Suan </option>
    <option value="Tubara"> Tubara </option>
    <option value="Usiacuri"> Usiacuri </option>
    ';
}
if ($dato=='Bogota D.C') {
    $options= '
    <option value="Bogota D.C"> Bogota D.C </option>
    ';
}
if ($_POST["elegido"]=="Bolívar") {
    $options= '
    <option value="Cartagena"> Cartagena </option>
    <option value="Achi"> Achi </option>
    <option value="Altos del Rosario"> Altos del Rosario </option>
    <option value="Arenal"> Arenal </option>
    <option value="Arjona"> Arjona </option>
    <option value="Arroyohondo"> Arroyohondo </option>
    <option value="Barranco de Loba"> Barranco de Loba </option>
    <option value="Calamar"> Calamar </option>
    <option value="Cantagallo"> Cantagallo </option>
    <option value="Cicuco"> Cicuco </option>
    <option value="Cordoba"> Cordoba </option>
    <option value="Clemencia"> Clemencia </option>
    <option value="El Carmen de Bolivar"> El Carmen de Bolivar </option>
    <option value="El Guamo"> El Guamo </option>
    <option value="El Peñon"> El Peñon </option>
    <option value="Hatillo de Loba"> Hatillo de Loba </option>
    <option value="Magangue"> Magangue </option>
    <option value="Mahates"> Mahates </option>
    <option value="Margarita"> Margarita </option>
    <option value="Maria la Baja"> Maria la Baja </option>
    <option value="Montecristo"> Montecristo </option>
    <option value="Mompos"> Mompos </option>
    <option value="Norosi"> Norosi </option>
    <option value="Morales"> Morales </option>
    <option value="Pinillos"> Pinillos </option>
    <option value="Regidor"> Regidor </option>
    <option value="Rio Viejo"> Rio Viejo </option>
    <option value="San Cristobal"> San Cristobal </option>
    <option value="San Estanislao"> San Estanislao </option>
    <option value="San Fernando"> San Fernando </option>
    <option value="San Jacinto"> San Jacinto </option>
    <option value="San Jacinto de Cauca"> San Jacinto de Cauca </option>
    <option value="San Juan de Nepomuceno"> San Juan de Nepomuceno </option>
    <option value="San Martin de Loba"> San Martin de Loba </option>
    <option value="San Pablo"> San Pablo </option>
    <option value="Santa Catalina"> Santa Catalina </option>
    <option value="Santa Rosa"> Santa Rosa </option>
    <option value="Santa Rosa del Sur"> Santa Rosa del Sur </option>
    <option value="Simiti"> Simiti </option>
    <option value="Soplaviento"> Soplaviento </option>
    <option value="Talaigua Nuevo"> Talaigua Nuevo </option>
    <option value="Tiquisio"> Tiquisio </option>
    <option value="Turbaco"> Turbaco </option>
    <option value="Turbana"> Turbana </option>
    <option value="Villanueva"> Villanueva </option>
    <option value="Zambrano"> Zambrano </option>
    ';
}
if ($_POST["elegido"]=="Boyacá") {
    $options= '
    <option value="Tunja"> Tunja </option>
    <option value="Almeida"> Almeida </option>
    <option value="Aquitania"> Aquitania </option>
    <option value="Arcabuco"> Arcabuco </option>
    <option value="Belen"> Belen </option>
    <option value="Berbeo"> Berbeo </option>
    <option value="Beteitiva"> Beteitiva </option>
    <option value="Boavita"> Boavita </option>
    <option value="Boyaca"> Boyaca </option>
    <option value="Briceño"> Briceño </option>
    <option value="Buenavista"> Buenavista </option>
    <option value="Busbanza"> Busbanza </option>
    <option value="Caldas"> Caldas </option>
    <option value="Campohermoso"> Campohermoso </option>
    <option value="Cerinza"> Cerinza </option>
    <option value="Chinavita"> Chinavita </option>
    <option value="Chiquinquira"> Chiquinquira </option>
    <option value="Chiscas"> Chiscas </option>
    <option value="Chita"> Chita </option>
    <option value="Chitaraque"> Chitaraque </option>
    <option value="Chivata"> Chivata </option>
    <option value="Cienaga"> Cienaga </option>
    <option value="Combita"> Combita </option>
    <option value="Coper"> Coper </option>
    <option value="Corrales"> Corrales </option>
    <option value="Covarachia"> Covarachia </option>
    <option value="Cubara"> Cubara </option>
    <option value="Cucaita"> Cucaita </option>
    <option value="Cuitiva"> Cuitiva </option>
    <option value="Chiquiza"> Chiquiza </option>
    <option value="Chivor"> Chivor </option>
    <option value="Duitama"> Duitama </option>
    <option value="El Cucuy"> El Cucuy </option>
    <option value="El Espino"> El Espino </option>
    <option value="Firavitoba"> Firavitoba </option>
    <option value="Floresta"> Floresta </option>
    <option value="Gachantiva"> Gachantiva </option>
    <option value="Gameza"> Gameza </option>
    <option value="Garagoa"> Garagoa </option>
    <option value="Guacamayas"> Guacamayas </option>
    <option value="Guateque"> Guateque </option>
    <option value="Guayata"> Guayata </option>
    <option value="Gican"> Gican </option>
    <option value="Iza"> Iza </option>
    <option value="Jenesano"> Jenesano </option>
    <option value="Jerico"> Jerico </option>
    <option value="Labranzagrande"> Labranzagrande </option>
    <option value="La Capilla"> La Capilla </option>
    <option value="La Victoria"> La Victoria </option>
    <option value="La Uvita"> La Uvita </option>
    <option value="Villa de Leyva"> Villa de Leyva </option>
    <option value="Macanal"> Macanal </option>
    <option value="Maripi"> Maripi </option>
    <option value="Miraflores"> Miraflores </option>
    <option value="Mongua"> Mongua </option>
    <option value="Mongui"> Mongui </option>
    <option value="Moniquira"> Moniquira </option>
    <option value="Motavita"> Motavita </option>
    <option value="Muzo"> Muzo </option>
    <option value="Nobsa"> Nobsa </option>
    <option value="Nuevo Colon"> Nuevo Colon </option>
    <option value="Oicata"> Oicata </option>
    <option value="Otanche"> Otanche </option>
    <option value="Pachavita"> Pachavita </option>
    <option value="Paez"> Paez </option>
    <option value="Paipa"> Paipa </option>
    <option value="Pajarito"> Pajarito </option>
    <option value="Panqueba"> Panqueba </option>
    <option value="Pauna"> Pauna </option>
    <option value="Paya"> Paya </option>
    <option value="Pez de Rio"> Pez de Rio </option>
    <option value="Pesca"> Pesca </option>
    <option value="Pisba"> Pisba </option>
    <option value="Pisba"> Puerto Boyaca </option>
    <option value="Quipama"> Quipama </option>
    <option value="Ramiriqui"> Ramiriqui </option>
    <option value="Raquira"> Raquira </option>
    <option value="Saboya"> Saboya </option>
    <option value="Sachica"> Sachica </option>
    <option value="Samaca"> Samaca </option>
    <option value="San Eduardo"> San Eduardo </option>
    <option value="San Jose de Pare"> San Jose de Pare </option>
    <option value="San Luis de Gaceno"> San Luis de Gaceno </option>
    <option value="San Mateo"> San Mateo </option>
    <option value="San Miguel de Sema"> San Miguel de Sema </option>
    <option value="San Pablo de Borbur"> San Pablo de Borbur </option>
    <option value="Santana"> Santana </option>
    <option value="Santa Maria"> Santa Maria </option>
    <option value="Santa Rosa de Viterbo"> Santa Rosa de Viterbo </option>
    <option value="Santa Sofia"> Santa Sofia </option>
    <option value="Sativa Norte"> Sativa Norte </option>
    <option value="Sativa Sur"> Sativa Sur </option>
    <option value="Siachoque"> Siachoque </option>
    <option value="Soata"> Soata </option>
    <option value="Socota"> Socota </option>
    <option value="Socha"> Socha </option>
    <option value="Sogamoso"> Sogamoso </option>
    <option value="Somondoco"> Somondoco </option>
    <option value="Sora"> Sora </option>
    <option value="Sotaquira"> Sotaquira </option>
    <option value="Soraca"> Soraca </option>
    <option value="Susacon"> Susacon </option>
    <option value="Sutamarchan"> Sutamarchan </option>
    <option value="Sutatenza"> Sutatenza </option>
    <option value="Tasco"> Tasco </option>
    <option value="Tenza"> Tenza </option>
    <option value="Tibana"> Tibana </option>
    <option value="Tibasosa"> Tibasosa </option>
    <option value="Tinjaca"> Tinjaca </option>
    <option value="Tipacoque"> Tipacoque </option>
    <option value="Toca"> Toca </option>
    <option value="Toga"> Toga </option>
    <option value="Topaga"> Topaga </option>
    <option value="Tota"> Tota </option>
    <option value="Tunungua"> Tunungua </option>
    <option value="Tuta"> Tuta </option>
    <option value="Tutaza"> Tutaza </option>
    <option value="Umbita"> Umbita </option>
    <option value="Ventaquemada"> Ventaquemada </option>
    <option value="Viracacha"> Viracacha </option>
    <option value="Zetaquira"> Zetaquira </option>
    ';
}
if ($_POST["elegido"]=="Caldas") {
    $options= '
    <option value="Manizales"> Manizales </option>
    <option value="Aguadas"> Aguadas </option>
    <option value="Anserma"> Anserma </option>
    <option value="Aranzazu"> Aranzazu </option>
    <option value="Belalcazar"> Belalcazar </option>
    <option value="Chinchina"> Chinchina </option>
    <option value="Filadelfia"> Filadelfia </option>
    <option value="La Dorada"> La Dorada </option>
    <option value="La Merced"> La Merced </option>
    <option value="Manzanares"> Manzanares </option>
    <option value="Marmato"> Marmato </option>
    <option value="Marquetalia"> Marquetalia </option>
    <option value="Marulanda"> Marulanda </option>
    <option value="Neira"> Neira </option>
    <option value="Norcasia"> Norcasia </option>
    <option value="Pecora"> Pecora </option>
    <option value="Palestina"> Palestina </option>
    <option value="Pensilvania"> Pensilvania </option>
    <option value="Riosucio"> Riosucio </option>
    <option value="Risaralda"> Risaralda </option>
    <option value="Salamina"> Salamina </option>
    <option value="San Jose"> San Jose </option>
    <option value="Supia"> Supia </option>
    <option value="Victoria"> Victoria </option>
    <option value="Villamaria"> Villamaria </option>
    <option value="Viterbo"> Viterbo </option>
    ';
}
if ($_POST["elegido"]=="Caquetá") {
    $options= '
    <option value="Florencia"> Florencia </option>
    <option value="Albania"> Albania </option>
    <option value="Belen de Los Andaquies"> Belen de Los Andaquies </option>
    <option value="Cartagena del Chaira"> Cartagena del Chaira </option>
    <option value="Curillo"> Curillo </option>
    <option value="El Doncello"> El Doncello </option>
    <option value="El Paujil"> El Paujil </option>
    <option value="La Montañita"> La Montañita </option>
    <option value="Milan"> Milan </option>
    <option value="Morelia"> Morelia </option>
    <option value="Puerto Rico"> Puerto Rico </option>
    <option value="San Jose del Fragua"> San Jose del Fragua </option>
    <option value="San Vicente del Caguan"> San Vicente del Caguan </option>
    <option value="Salono"> Salono </option>
    <option value="Solita"> Solita </option>
    <option value="Valparaiso"> Valparaiso </option>
    ';
}
if ($_POST["elegido"]=="Casanare") {
    $options= '
    <option value="Yopal"> Yopal </option>
    <option value="Aguazul Aguazul </option>
    <option value="Chameza"> Chameza </option>
    <option value="Hato Corozal"> Hato Corozal </option>
    <option value="La Salina"> La Salina </option>
    <option value="Mani"> Mani </option>
    <option value="Monterrey"> Monterrey </option>
    <option value="Nunchia"> Nunchia </option>
    <option value="Orocue"> Orocue </option>
    <option value="Paz de Ariporo"> Paz de Ariporo </option>
    <option value="Pore"> Pore </option>
    <option value="Recetor"> Recetor </option>
    <option value="Sabanalarga"> Sabanalarga </option>
    <option value="Sacana"> Sacana </option>
    <option value="San Luis de Palenque"> San Luis de Palenque </option>
    <option value="Tamara"> Tamara </option>
    <option value="Tauramena"> Tauramena </option>
    <option value="Trinidad"> Trinidad </option>
    <option value="Villanueva"> Villanueva </option>
    ';
}
if ($_POST["elegido"]=="Cauca") {
    $options= '
    <option value="Popayan"> Popayan </option>
    <option value="Almaguer"> Almaguer </option>
    <option value="Argelia"> Argelia </option>
    <option value="Balboa"> Balboa </option>
    <option value="Bolivar"> Bolivar </option>
    <option value="Buenos Aires"> Buenos Aires </option>
    <option value="Cajibio"> Cajibio </option>
    <option value="Caldono"> Caldono </option>
    <option value="Caloto"> Caloto </option>
    <option value="Corinto"> Corinto </option>
    <option value="El Tambo"> El Tambo </option>
    <option value="Florencia"> Florencia </option>
    <option value="Guachene"> Guachene </option>
    <option value="Guapi"> Guapi </option>
    <option value="Inza"> Inza </option>
    <option value="Jambalo"> Jambalo </option>
    <option value="La Sierra"> La Sierra </option>
    <option value="La Vega"> La Vega </option>
    <option value="Lopez"> Lopez </option>
    <option value="Mercaderes"> Mercaderes </option>
    <option value="Miranda"> Miranda </option>
    <option value="Morales"> Morales </option>
    <option value="Padilla"> Padilla </option>
    <option value="Paez"> Paez </option>
    <option value="Patia"> Patia </option>
    <option value="Piamonte"> Piamonte </option>
    <option value="Piendamo"> Piendamo </option>
    <option value="Puerto Tejada"> Puerto Tejada </option>
    <option value="Purace"> Purace </option>
    <option value="Rosas"> Rosas </option>
    <option value="San Sebastian"> San Sebastian </option>
    <option value="Santander de Quilichao"> Santander de Quilichao </option>
    <option value="Santa Rosa"> Santa Rosa </option>
    <option value="Silvia"> Silvia </option>
    <option value="Sotara"> Sotara </option>
    <option value="Suarez"> Suarez </option>
    <option value="Sucre"> Sucre </option>
    <option value="Timbio"> Timbio </option>
    <option value="Timbiqui"> Timbiqui </option>
    <option value="Toribio"> Toribio </option>
    <option value="Totoro"> Totoro </option>
    <option value="Villa Rica"> Villa Rica </option>
    ';
}
if ($_POST["elegido"]=="Cesar") {
    $options= '
    <option value="Valledupar"> Valledupar </option>
    <option value="Aguachica">  </option>
    <option value="Agustin Codazzi"> Agustin Codazzi </option>
    <option value="Astrea"> Astrea </option>
    <option value="Becerril"> Becerril </option>
    <option value="Bosconia"> Bosconia </option>
    <option value="Chimichagua"> Chimichagua </option>
    <option value="Chiriguana"> Chiriguana </option>
    <option value="Curumani"> Curumani </option>
    <option value="El Copey"> El Copey </option>
    <option value="El Paso"> El Paso </option>
    <option value="Gamarra"> Gamarra </option>
    <option value="Gonzalez"> Gonzalez </option>
    <option value="La Gloria"> La Gloria </option>
    <option value="La Jagua de Ibirico"> La Jagua de Ibirico </option>
    <option value="La Paz"> La Paz </option>
    <option value="Manaure"> Manaure </option>
    <option value="Pailitas"> Pailitas </option>
    <option value="Pelaya"> Pelaya </option>
    <option value="Pueblo Bello"> Pueblo Bello </option>
    <option value="Rio de Oro"> Rio de Oro </option>
    <option value="San Alberto"> San Alberto </option>
    <option value="San Diego"> San Diego </option>
    <option value="San Martin"> San Martin </option>
    <option value="Tamalameque"> Tamalameque </option>
    ';
}
if ($_POST["elegido"]=="Chocó") {
    $options= '
    <option value="Quibdo"> Quibdo </option>
    <option value="Acandi"> Acandi </option>
    <option value="Alto Baudo"> Alto Baudo </option>
    <option value="Atrato"> Atrato </option>
    <option value="Bagado"> Bagado </option>
    <option value="Bahia Solano"> Bahia Solano </option>
    <option value="Bajo Baudo"> Bajo Baudo </option>
    <option value="Bojaya"> Bojaya </option>
    <option value="Carmen del Darien"> Carmen del Darien </option>
    <option value="Certegui"> Certegui </option>
    <option value="Condoto"> Condoto </option>
    <option value="El Canton del San Pablo"> El Canton del San Pablo </option>
    <option value="El Carmen de Atrato"> El Carmen de Atrato </option>
    <option value="El Litoral del San Juan"> El Litoral del San Juan </option>
    <option value="Itsmina"> Itsmina </option>
    <option value="Jurado"> Jurado </option>
    <option value="Lloro"> Lloro </option>
    <option value="Medio Atrato"> Medio Atrato </option>
    <option value="Medio Baudo"> Medio Baudo </option>
    <option value="Medio San Juan"> Medio San Juan </option>
    <option value="Novita"> Novita </option>
    <option value="Nuqui"> Nuqui </option>
    <option value="Rio Iro"> Rio Iro </option>
    <option value="Rio Quito"> Rio Quito </option>
    <option value="Riosucio"> Riosucio </option>
    <option value="San Jose del Palmar"> San Jose del Palmar </option>
    <option value="Sipi"> Sipi </option>
    <option value="Tado"> Tado </option>
    <option value="Unguia"> Unguia </option>
    <option value="Unión Panamericana"> Unión Panamericana </option>
    ';
}
if ($_POST["elegido"]=="Córdoba") {
    $options= '
    <option value="Monteria"> Monteria </option>
    <option value="Ayapel"> Ayapel </option>
    <option value="Buenavista"> Buenavista </option>
    <option value="Canalete"> Canalete </option>
    <option value="Cerete"> Cerete </option>
    <option value="Chima"> Chima </option>
    <option value="Chima"> Chinu </option>
    <option value="Cienaga de Oro"> Cienaga de Oro </option>
    <option value="Cotorra"> Cotorra </option>
    <option value="La Apartada"> La Apartada </option>
    <option value="Lorica"> Lorica </option>
    <option value="Los Cordobas"> Los Cordobas </option>
    <option value="Momil"> Momil </option>
    <option value="Montelibano"> Montelibano </option>
    <option value="Moñitos"> Moñitos </option>
    <option value="Planeta Rica"> Planeta Rica </option>
    <option value="Pueblo Nuevo"> Pueblo Nuevo </option>
    <option value="Puerto Escondido"> Puerto Escondido </option>
    <option value="Puerto Libertador"> Puerto Libertador </option>
    <option value="Purisima"> Purisima </option>
    <option value="Sahagun"> Sahagun </option>
    <option value="San Andres Sotavento"> San Andres Sotavento </option>
    <option value="San Antero"> San Antero </option>
    <option value="San Bernardo del Viento"> San Bernardo del Viento </option>
    <option value="San Carlos"> San Carlos </option>
    <option value="San Pelayo"> San Pelayo </option>
    <option value="TierraAlta"> TierraAlta </option>
    <option value="Valencia"> Valencia </option>
    ';
}
if ($_POST["elegido"]=="Cundinamarca") {
    $options= '
    <option value="Agua de Dios"> Agua de Dios </option>
    <option value="Alban"> Alban </option>
    <option value="Anapoima"> Anapoima </option>
    <option value="Anolaima "> Anolaima </option>
    <option value="Arbelaez"> Arbelaez </option>
    <option value="Beltran"> Beltran </option>
    <option value="Bituima"> Bituima </option>
    <option value="Bojaca"> Bojaca </option>
    <option value="Cabrera"> Cabrera </option>
    <option value="Cachipay"> Cachipay </option>
    <option value="Cajica"> Cajica </option>
    <option value="Ayapel"> Ayapel </option>
    <option value="Caparrapi"> Caparrapi </option>
    <option value="Caqueza"> Caqueza </option>
    <option value="Carmen de Carupa"> Carmen de Carupa </option>
    <option value="Chaguani"> Chaguani </option>
    <option value="Chia"> Chia </option>
    <option value="Chipaque"> Chipaque </option>
    <option value="Choachi"> Choachi </option>
    <option value="Choconta"> Choconta </option>
    <option value="Cogua"> Cogua </option>
    <option value="Cota"> Cota </option>
    <option value="Cucunuba"> Cucunuba </option>
    <option value="El Colegio"> El Colegio </option>
    <option value="El Peñon"> El Peñon </option>
    <option value="El Rosal"> El Rosal </option>
    <option value="Facatativa"> Facatativa </option>
    <option value="Fomeque"> Fomeque </option>
    <option value="Fosca"> Fosca </option>
    <option value="Funza"> Funza </option>
    <option value="Fuquene"> Fuquene </option>
    <option value="Fusagasuga"> Fusagasuga </option>
    <option value="Gachala"> Gachala </option>
    <option value="Gachancipa"> Gachancipa </option>
    <option value="Gacheta"> Gacheta </option>
    <option value="Girardot"> Girardot </option>
    <option value="Guaduas"> Guaduas </option>
    <option value="Guasca"> Guasca </option>
    <option value="Guataqui"> Guataqui </option>
    <option value="Guatavita"> Guatavita </option>
    <option value="Guayabal de Siquima"> Guayabal de Siquima </option>
    <option value="Guayabetal"> Guayabetal </option>
    <option value="Guitierrez"> Guitierrez </option>
    <option value="Jerusalen"> Jerusalen </option>
    <option value="Junin"> Junin </option>
    <option value="La Calera"> La Calera </option>
    <option value="La Mesa"> La Mesa </option>
    <option value="La Palma"> La Palma </option>
    <option value="La Peña"> La Peña </option>
    <option value="La Vega"> La Vega </option>
    <option value="Lenguazaque"> Lenguazaque </option>
    <option value="Macheta"> Macheta </option>
    <option value="Madrid"> Madrid </option>
    <option value="Manta"> Manta </option>
    <option value="Medina"> Medina </option>
    <option value="Mosquera"> Mosquera </option>
    <option value="Nariño"> Nariño </option>
    <option value="Nemocon"> Nemocon </option>
    <option value="Nilo"> Nilo </option>
    <option value="Ninaima"> Ninaima </option>
    <option value="Nocaima"> Nocaima </option>
    <option value="Venecia"> Venecia </option>
    <option value="Pacho"> Pacho </option>
    <option value="Paime"> Paime </option>
    <option value="Pandi"> Pandi </option>
    <option value="Paratebueno"> Paratebueno </option>
    <option value="Pasca"> Pasca </option>
    <option value="Puerto Salgar"> Puerto Salgar </option>
    <option value="Puli"> Puli </option>
    <option value="Quebradanegra"> Quebradanegra </option>
    <option value="Quetame"> Quetame </option>
    <option value="Quipile"> Quipile </option>
    <option value="Apulo"> Apulo </option>
    <option value="Ricaurte"> Ricaurte </option>
    <option value="San Antonio del Tequendama"> San Antonio del Tequendama </option>
    <option value="San Bernardo"> San Bernardo </option>
    <option value="San Cayetano"> San Cayetano </option>
    <option value="San Francisco"> San Francisco </option>
    <option value="San Juan de Rio Seco"> San Juan de Rio Seco </option>
    <option value="Sasaima"> Sasaima </option>
    <option value="Sesquile"> Sesquile </option>
    <option value="Sibate"> Sibate </option>
    <option value="Silvania"> Silvania </option>
    <option value="Simijaca"> Simijaca </option>
    <option value="Soacha"> Soacha </option>
    <option value="Sopo"> Sopo </option>
    <option value="Subachoque"> Subachoque </option>
    <option value="Suesca"> Suesca </option>
    <option value="Supata"> Supata </option>
    <option value="Susa"> Susa </option>
    <option value="Sutatausa"> Sutatausa </option>
    <option value="Tabio"> Tabio </option>
    <option value="Tausa"> Tausa </option>
    <option value="Tena"> Tena </option>
    <option value="Tenjo"> Tenjo </option>
    <option value="Tibacuy"> Tibacuy </option>
    <option value="Tibirita"> Tibirita </option>
    <option value="Tocaima"> Tocaima </option>
    <option value="Tocancipa"> Tocancipa </option>
    <option value="Ubaque"> Ubaque </option>
    <option value="Villa de San Diego de Ubate"> Villa de San Diego de Ubate </option>
    <option value="Une"> Une </option>
    <option value="Utica"> Utica </option>
    <option value="Vergara"> Vergara </option>
    <option value="Viani"> Viani </option>
    <option value="Villagomez"> Villagomez </option>
    <option value="Villapinzon"> Villapinzon </option>
    <option value="Villeta"> Villeta </option>
    <option value="Viota"> Viota </option>
    <option value="Yacopí"> Yacopí </option>
    <option value="Zipacon"> Zipacon </option>
    <option value="Zipaquira"> Zipaquira </option>
    ';
}
if ($_POST["elegido"]=="Guainía") {
    $options= '
    <option value="Inirida"> Inirida </option>
    <option value="Barranco Minas"> Barranco Minas </option>
    <option value="Mapiripana"> Mapiripana </option>
    <option value="San Felipe"> San Felipe </option>
    <option value="Puerto Colombia"> Puerto Colombia </option>
    <option value="La Guadalupe"> La Guadalupe </option>
    <option value="Cacahual"> Cacahual </option>
    <option value="Pana Pana"> Pana Pana </option>
    <option value="Morichal"> Morichal </option>
    ';
}
if ($_POST["elegido"]=="Guaviare") {
    $options= '
    <option value="San Jose del Guaviare"> San Jose del Guaviare </option>
    <option value="Calamar"> Calamar </option>
    <option value="El Retorno"> El Retorno </option>
    <option value="Miraflores"> Miraflores </option>
    ';
}
if ($_POST["elegido"]=="Huila") {
    $options= '
    <option value="Neiva"> Neiva </option>
    <option value="Acevedo"> Acevedo </option>
    <option value="Agrado"> Agrado </option>
    <option value="Aipe"> Aipe </option>
    <option value="Algeciras"> Algeciras </option>
    <option value="Altamira"> Altamira </option>
    <option value="Baraya"> Baraya </option>
    <option value="Campoalegre"> Campoalegre </option>
    <option value="Colombia"> Colombia </option>
    <option value="Elias"> Elias </option>
    <option value="Garzon"> Garzon </option>
    <option value="Gigante"> Gigante </option>
    <option value="Guadalupe"> Guadalupe </option>
    <option value="Hobo"> Hobo </option>
    <option value="Iquira"> Iquira </option>
    <option value="Isnos"> Isnos </option>
    <option value="La Argentina"> La Argentina </option>
    <option value="La Plata"> La Plata </option>
    <option value="Natagana"> Natagana </option>
    <option value="Oporapa"> Oporapa </option>
    <option value="Paicol"> Paicol </option>
    <option value="Palermo"> Palermo </option>
    <option value="Palestina"> Palestina </option>
    <option value="Pital"> Pital </option>
    <option value="Pitalito"> Pitalito </option>
    <option value="Rivera"> Rivera </option>
    <option value="SaladoBlanco"> SaladoBlanco </option>
    <option value="San Agustin"> San Agustin </option>
    <option value="Santa Maria"> Santa Maria </option>
    <option value="Suaza"> Suaza </option>
    <option value="Tarqui"> Tarqui </option>
    <option value="Tesalia"> Tesalia </option>
    <option value="Tello"> Tello </option>
    <option value="Teruel"> Teruel </option>
    <option value="Timana"> Timana </option>
    <option value="Villanueva"> Villanueva </option>
    <option value="Yaguara"> Yaguara </option>
    ';
}
if ($_POST["elegido"]=="La Guajira") {
    $options= '
    <option value="Riohacha"> Riohacha </option>
    <option value="Albania"> Albania </option>
    <option value="Barrancas"> Barrancas </option>
    <option value="Dibulla"> Dibulla </option>
    <option value="Distracción"> Distracción </option>
    <option value="El Molino"> El Molino </option>
    <option value="Fonseca"> Fonseca </option>
    <option value="Hatonuevo"> Hatonuevo </option>
    <option value="La Jagua del Pilar"> La Jagua del Pilar </option>
    <option value="Maicao"> Maicao </option>
    <option value="Manaure"> Manaure </option>
    <option value="San Juan del Cesar"> San Juan del Cesar </option>
    <option value="Uribia"> Uribia </option>
    <option value="Urumita"> Urumita </option>
    <option value="Villanueva"> Villanueva </option>
    ';
}
if ($_POST["elegido"]=="Magdalena") {
    $options= '
    <option value="Santa Marta"> Santa Marta </option>
    <option value="Algarrobo"> Algarrobo </option>
    <option value="Aracataca"> Aracataca </option>
    <option value="Ariguani"> Ariguani </option>
    <option value="Cerro San Antonio"> Cerro San Antonio </option>
    <option value="Chibolo"> Chibolo </option>
    <option value="Cienaga"> Cienaga </option>
    <option value="Concorida"> Concorida </option>
    <option value="El Banco"> El Banco </option>
    <option value="El Piñon"> El Piñon </option>
    <option value="El Reten"> El Reten </option>
    <option value="Fundación"> Fundación </option>
    <option value="Guamal"> Guamal </option>
    <option value="Nueva Granada"> Nueva Granada </option>
    <option value="Pedraza"> Pedraza </option>
    <option value="Pujiño del Carmen"> Pujiño del Carmen </option>
    <option value="Pivijay"> Pivijay </option>
    <option value="Plato"> Plato </option>
    <option value="PuebloViejo"> PuebloViejo </option>
    <option value="Remolino"> Remolino </option>
    <option value="Sabanas de San Angel"> Sabanas de San Angel </option>
    <option value="Salamina"> Salamina </option>
    <option value="San Sebastian de Buenavista"> San Sebastian de Buenavista </option>
    <option value="San Zenon"> San Zenon </option>
    <option value="Santa Ana"> Santa Ana </option>
    <option value="Santa Barbara de Pinto"> Santa Barbara de Pinto </option>
    <option value="Sitionuevo"> Sitionuevo </option>
    <option value="Tenefife"> Tenefife </option>
    <option value="Zapayan"> Zapayan </option>
    <option value="Zona Bananera"> Zona Bananera </option>
    ';
}
if ($_POST["elegido"]=="Meta") {
    $options= '
    <option value="Villavicencio"> Villavicencio </option>
    <option value="Acacias"> Acacias </option>
    <option value="Barranca de Upia"> Barranca de Upia </option>
    <option value="Cabuyaro"> Cabuyaro </option>
    <option value="Castilla La Nueva"> Castilla La Nueva </option>
    <option value="Cubarral"> Cubarral </option>
    <option value="Cumaral"> Cumaral </option>
    <option value="El Calvario"> El Calvario </option>
    <option value="El Castillo"> El Castillo </option>
    <option value="El Dorado"> El Dorado </option>
    <option value="Fuente de Oro"> Fuente de Oro </option>
    <option value="Granada"> Granada </option>
    <option value="Guamal"> Guamal </option>
    <option value="Mipiripan"> Mipiripan </option>
    <option value="Mesetas"> Mesetas </option>
    <option value="La Macarena"> La Macarena </option>
    <option value="Uribe"> Uribe </option>
    <option value="Lejanias"> Lejanias </option>
    <option value="Puerto Concordia"> Puerto Concordia </option>
    <option value="Puerto Gaitan"> Puerto Gaitan </option>
    <option value="Puerto Lopez"> Puerto Lopez </option>
    <option value="Puerto Lleras"> Puerto Lleras </option>
    <option value="Puerto Rico"> Puerto Rico </option>
    <option value="Restrepo"> Restrepo </option>
    <option value="San Carlos de Guarda"> San Carlos de Guarda </option>
    <option value="San Juan de Arama"> San Juan de Arama </option>
    <option value="San Juanito"> San Juanito </option>
    <option value="San Martin"> San Martin </option>
    <option value="Vistahermosa"> Vistahermosa </option>
    ';
}
if ($_POST["elegido"]=="Nariño") {
    $options= '
    <option value="Pasto"> Pasto </option>
    <option value="Alban"> Alban </option>
    <option value="Aldana"> Aldana </option>
    <option value="Ancuya"> Ancuya </option>
    <option value="Arboleda"> Arboleda </option>
    <option value="Barbacoas"> Barbacoas </option>
    <option value="Belen"> Belen </option>
    <option value="Buesaco"> Buesaco </option>
    <option value="Colon"> Colon </option>
    <option value="Consaca"> Consaca </option>
    <option value="Contedero"> Contedero </option>
    <option value="Cordoba"> Cordoba </option>
    <option value="Cuaspud"> Cuaspud </option>
    <option value="Cumbal"> Cumbal </option>
    <option value="Combitara"> Combitara </option>
    <option value="Chachaga"> Chachaga </option>
    <option value="El Charco"> El Charco </option>
    <option value="El Peñol"> El Peñol </option>
    <option value="El Rosario"> El Rosario </option>
    <option value="El Tablón de Gomez"> El Tablón de Gomez </option>
    <option value="El Tambo"> El Tambo </option>
    <option value="Funes"> Funes </option>
    <option value="Guachucal"> Guachucal </option>
    <option value="Guaitarilla"> Guaitarilla </option>
    <option value="Gualmatan"> Gualmatan </option>
    <option value="Iles"> Iles </option>
    <option value="Imues"> Imues </option>
    <option value="Ipiales"> Ipiales </option>
    <option value="La Cruz"> La Cruz </option>
    <option value="La Florida"> La Florida </option>
    <option value="La LLanada"> La LLanada </option>
    <option value="La Tola"> La Tola </option>
    <option value="La Unión"> La Unión </option>
    <option value="Leiva"> Leiva </option>
    <option value="Linares"> Linares </option>
    <option value="Maga"> Maga </option>
    <option value="Mallama"> Mallama </option>
    <option value="Mosquera"> Mosquera </option>
    <option value="Nariño"> Nariño </option>
    <option value="Olaya Herrera"> Olaya Herrera </option>
    <option value="Ospina"> Ospina </option>
    <option value="Francisco Pizarro"> Francisco Pizarro </option>
    <option value="Policarpa"> Policarpa </option>
    <option value="Potosi"> Potosi </option>
    <option value="Providencia"> Providencia </option>
    <option value="Puerres"> Puerres </option>
    <option value="Pupiales"> Pupiales </option>
    <option value="Ricaurte"> Ricaurte </option>
    <option value="Roberto Payan"> Roberto Payan </option>
    <option value="Samaniego"> Samaniego </option>
    <option value="Sandona"> Sandona </option>
    <option value="San Bernardo"> San Bernardo </option>
    <option value="San Lorenzo"> San Lorenzo </option>
    <option value="San Pablo"> San Pablo </option>
    <option value="San Pedro de Cartago"> San Pedro de Cartago </option>
    <option value="Santa Barbara"> Santa Barbara </option>
    <option value="SantaCruz"> SantaCruz </option>
    <option value="Sapuyes"> Sapuyes </option>
    <option value="Taminango"> Taminango </option>
    <option value="Tangua"> Tangua </option>
    <option value="San Andres de Tumaco"> San Andres de Tumaco </option>
    <option value="Tuquerres"> Tuquerres </option>
    <option value="Yacuanquer"> Yacuanquer </option>
    ';
}
if ($_POST["elegido"]=="Norte de Santander") {
    $options= '
    <option value="Cucuta"> Cucuta </option>
    <option value="Abrego"> Abrego </option>
    <option value="Arboledas"> Arboledas </option>
    <option value="Bochalema"> Bochalema </option>
    <option value="Bucarasica"> Bucarasica </option>
    <option value="Cacota"> Cacota </option>
    <option value="Cahira"> Cahira </option>
    <option value="Chinacota"> Chinacota </option>
    <option value="Chitaga"> Chitaga </option>
    <option value="Convención"> Convención </option>
    <option value="Cucutilla"> Cucutilla </option>
    <option value="Durania"> Durania </option>
    <option value="El Carmen"> El Carmen </option>
    <option value="El Tarra"> El Tarra </option>
    <option value="El Zulia"> El Zulia </option>
    <option value="Gramalote"> Gramalote </option>
    <option value="Hacari"> Hacari </option>
    <option value="Herran"> Herran </option>
    <option value="Labateca"> Labateca </option>
    <option value="La Esperanza"> La Esperanza </option>
    <option value="La Playa"> La Playa </option>
    <option value="Los Patios"> Los Patios </option>
    <option value="Lourdes"> Lourdes </option>
    <option value="Mutiscua"> Mutiscua </option>
    <option value="Ocaña"> Ocaña </option>
    <option value="Pamplona"> Pamplona </option>
    <option value="Pamplonita"> Pamplonita </option>
    <option value="Puerto Santander"> Puerto Santander </option>
    <option value="Rangonvalia"> Rangonvalia </option>
    <option value="Salazar"> Salazar </option>
    <option value="San Calixto"> San Calixto </option>
    <option value="San Cayetano"> San Cayetano </option>
    <option value="Santiago"> Santiago </option>
    <option value="Sardinata"> Sardinata </option>
    <option value="Silos"> Silos </option>
    <option value="Teorama"> Teorama </option>
    <option value="Tibu"> Tibu </option>
    <option value="Toledo"> Toledo </option>
    <option value="Villa Caro"> Villa Caro </option>
    <option value="Villa del Rosario"> Villa del Rosario </option>
    ';
}
if ($_POST["elegido"]=="Putumayo") {
    $options= '
    <option value="Mocoa"> Mocoa </option>
    <option value="Colon"> Colon </option>
    <option value="Orito"> Orito </option>
    <option value="Puerto Asis"> Puerto Asis </option>
    <option value="Puerto Caicedo"> Puerto Caicedo </option>
    <option value="Puerto Guzman"> Puerto Guzman </option>
    <option value="Leguizamo"> Leguizamo </option>
    <option value="Sibundoy"> Sibundoy </option>
    <option value="San Francisco"> San Francisco </option>
    <option value="San Miguel"> San Miguel </option>
    <option value="Santiago"> Santiago </option>
    <option value="Valle de Guamuez"> Valle de Guamuez </option>
    <option value="Villagarzon"> Villagarzon </option>
    ';
}
if ($_POST["elegido"]=="Quindio") {
    $options= '
    <option value="Armenia"> Armenia </option>
    <option value="Buenavista"> Buenavista </option>
    <option value="Calarca"> Calarca </option>
    <option value="Circasia"> Circasia </option>
    <option value="Cordoba"> Cordoba </option>
    <option value="Filandia"> Filandia </option>
    <option value="Genova"> Genova </option>
    <option value="La Tebaida"> La Tebaida </option>
    <option value="Montenegro"> Montenegro </option>
    <option value="Pijao"> Pijao </option>
    <option value="Qimbaya"> Qimbaya </option>
    <option value="Salento"> Salento </option>
    ';
}
if ($_POST["elegido"]=="Risaralda") {
    $options= '
    <option value="Pereira"> Pereira </option>
    <option value="Apia"> Apia </option>
    <option value="Balboa"> Balboa </option>
    <option value="Belen de Umbria"> Belen de Umbria </option>
    <option value="Dosquebradas"> Dosquebradas </option>
    <option value="Guatica"> Guatica </option>
    <option value="La Celia"> La Celia </option>
    <option value="La Virginia"> La Virginia </option>
    <option value="Marsella"> Marsella </option>
    <option value="Mistrato"> Mistrato </option>
    <option value="Pueblo Rico"> Pueblo Rico </option>
    <option value="Quinchia"> Quinchia </option>
    <option value="Santa Rosa de Cabal"> Santa Rosa de Cabal </option>
    <option value="Santuario"> Santuario </option>
    ';
}
if ($_POST["elegido"]=="San Andres") {
    $options= '
    <option value="San Andres"> San Andres </option>
    <option value="Providencia"> Providencia </option>
    ';
}
if ($_POST["elegido"]=="Santander") {
    $options= '
    <option value="Bucaramanga"> Bucaramanga </option>
    <option value="Aguada"> Aguada </option>
    <option value="Albania"> Albania </option>
    <option value="Aratoca"> Aratoca </option>
    <option value="Barbosa"> Barbosa </option>
    <option value="Barichara"> Barichara </option>
    <option value="Barrancabermeja"> Barrancabermeja </option>
    <option value="Betulia"> Betulia </option>
    <option value="Bolivar"> Bolivar </option>
    <option value="Cabrera"> Cabrera </option>
    <option value="California"> California </option>
    <option value="Capitanejo"> Capitanejo </option>
    <option value="Carcasi"> Carcasi </option>
    <option value="Cepita"> Cepita </option>
    <option value="Cerrito"> Cerrito </option>
    <option value="Charala"> Charala </option>
    <option value="Charta"> Charta </option>
    <option value="Chima"> Chima </option>
    <option value="Chipata"> Chipata </option>
    <option value="Cimitarra"> Cimitarra </option>
    <option value="Concepción"> Concepción </option>
    <option value="Confines"> Confines </option>
    <option value="Contratación"> Contratación </option>
    <option value="Coromoro"> Coromoro </option>
    <option value="Curiti"> Curiti </option>
    <option value="El Carmen de Chucuri"> El Carmen de Chucuri </option>
    <option value="El Guacamayo"> El Guacamayo </option>
    <option value="El Peñon"> El Peñon </option>
    <option value="El Playon"> El Playon </option>
    <option value="Encino"> Encino </option>
    <option value="Esciso"> Esciso </option>
    <option value="Florian"> Florian </option>
    <option value="Floridablanca"> Floridablanca </option>
    <option value="Galan"> Galan </option>
    <option value="Gambita"> Gambita </option>
    <option value="Girón"> Girón </option>
    <option value="Guaca"> Guaca </option>
    <option value="Guadalupe"> Guadalupe </option>
    <option value="Guapota"> Guapota </option>
    <option value="Guavata"> Guavata </option>
    <option value="Guepsa"> Guepsa </option>
    <option value="Hatillo"> Hatillo </option>
    <option value="Jesus Maria"> Jesus Maria </option>
    <option value="Jordan"> Jordan </option>
    <option value="La Belleza"> La Belleza </option>
    <option value="Landazuri"> Landazuri </option>
    <option value="La Paz"> La Paz </option>
    <option value="Lebrija"> Lebrija </option>
    <option value="Los Santos"> Los Santos </option>
    <option value="Macaravita"> Macaravita </option>
    <option value="Malaga"> Malaga </option>
    <option value="Matanza"> Matanza </option>
    <option value="Mogotes"> Mogotes </option>
    <option value="Molagavita"> Molagavita </option>
    <option value="Ocamonte"> Ocamonte </option>
    <option value="Oiba"> Oiba </option>
    <option value="Onzaga"> Onzaga </option>
    <option value="Palmar"> Palmar </option>
    <option value="Palmas del Socorro"> Palmas del Socorro </option>
    <option value="Paramo"> Paramo </option>
    <option value="Piedecuesta"> Piedecuesta </option>
    <option value="Pinchote"> Pinchote </option>
    <option value="Puente Nacional"> Puente Nacional </option>
    <option value="Puerto Parra"> Puerto Parra </option>
    <option value="Puerto Wilches"> Puerto Wilches </option>
    <option value="Rionegro"> Rionegro </option>
    <option value="Sabana de Torres"> Sabana de Torres </option>
    <option value="San Andres"> San Andres </option>
    <option value="San Benito"> San Benito </option>
    <option value="San Gil"> San Gil </option>
    <option value="San Juaquin"> San Juaquin </option>
    <option value="San Jose de Miranda"> San Jose de Miranda </option>
    <option value="San Miguel"> San Miguel </option>
    <option value="San Vicente del Chucuri"> San Vicente del Chucuri </option>
    <option value="Santa Barbara"> Santa Barbara </option>
    <option value="Santa Helena del Opon"> Santa Helena del Opon </option>
    <option value="Simacota"> Simacota </option>
    <option value="Socorro"> Socorro </option>
    <option value="Suaita"> Suaita </option>
    <option value="Sucre"> Sucre </option>
    <option value="Surata"> Surata </option>
    <option value="Tona"> Tona </option>
    <option value="Valle de San Jose"> Valle de San Jose </option>
    <option value="Velez"> Velez </option>
    <option value="Villanueva"> Villanueva </option>
    <option value="Zapatoca"> Zapatoca </option>
    ';
}
if ($_POST["elegido"]=="Sucre") {
    $options= '
    <option value="Sincelejo"> Sincelejo </option>
    <option value="Buenavista"> Buenavista </option>
    <option value="Caimito"> Caimito </option>
    <option value="Coloso"> Coloso </option>
    <option value="Corozal"> Corozal </option>
    <option value="Coveñas"> Coveñas </option>
    <option value="Chalan"> Chalan </option>
    <option value="El Roble"> El Roble </option>
    <option value="Galeras"> Galeras </option>
    <option value="Guaranda"> Guaranda </option>
    <option value="La Union"> La Union </option>
    <option value="Los Palmitos"> Los Palmitos </option>
    <option value="Majagual"> Majagual </option>
    <option value="Morroa"> Morroa </option>
    <option value="Ovejas"> Ovejas </option>
    <option value="Sampues"> Sampues </option>
    <option value="San Benito de Abad"> San Benito de Abad </option>
    <option value="San Juan de Betulia"> San Juan de Betulia </option>
    <option value="San Marcos"> San Marcos </option>
    <option value="San Onofre"> San Onofre </option>
    <option value="San Luis de Sincelejo"> San Luis de Sincelejo </option>
    <option value="Sucre"> Sucre </option>
    <option value="Santiago de Tolu"> Santiago de Tolu </option>
    <option value="Tolu Viejo"> Tolu Viejo </option>
    ';
}
if ($_POST["elegido"]=="Tolima") {
    $options= '
    <option value="Ibague"> Ibague </option>
    <option value="Alpujarra"> Alpujarra </option>
    <option value="Alvarado"> Alvarado </option>
    <option value="Ambalema"> Ambalema </option>
    <option value="Anzoategui"> Anzoategui </option>
    <option value="Armero"> Armero </option>
    <option value="Ataco"> Ataco </option>
    <option value="Cajamarca"> Cajamarca </option>
    <option value="Carmen de Apicala"> Carmen de Apicala </option>
    <option value="Casabianca"> Casabianca </option>
    <option value="Chaparral"> Chaparral </option>
    <option value="Coello"> Coello </option>
    <option value="Coyaima"> Coyaima </option>
    <option value="Cunday"> Cunday </option>
    <option value="Dolores"> Dolores </option>
    <option value="Espinal"> Espinal </option>
    <option value="Falan"> Falan </option>
    <option value="Flandes"> Flandes </option>
    <option value="Fresno"> Fresno </option>
    <option value="Guamo"> Guamo </option>
    <option value="Herveo"> Herveo </option>
    <option value="Honda"> Honda </option>
    <option value="Icononzo"> Icononzo </option>
    <option value="Lerida"> Lerida </option>
    <option value="Libano"> Libano </option>
    <option value="Mariquita"> Mariquita </option>
    <option value="Melgar"> Melgar </option>
    <option value="Natagaima"> Natagaima </option>
    <option value="Ortega"> Ortega </option>
    <option value="Palocabildo"> Palocabildo </option>
    <option value="Piedras"> Piedras </option>
    <option value="Planadas"> Planadas </option>
    <option value="Prado"> Prado </option>
    <option value="Purificación"> Purificación </option>
    <option value="Rioblanco"> Rioblanco </option>
    <option value="Roncesvalles"> Roncesvalles </option>
    <option value="Rovira"> Rovira </option>
    <option value="Saldaña"> Saldaña </option>
    <option value="San Antonio"> San Antonio </option>
    <option value="San Luis"> San Luis </option>
    <option value="Santa Isabel"> Santa Isabel </option>
    <option value="Suarez"> Suarez </option>
    <option value="Valle de San Juan"> Valle de San Juan </option>
    <option value="Venadillo"> Venadillo </option>
    <option value="Villahermosa"> Villahermosa </option>
    <option value="Villarrica"> Villarrica </option>
    ';
}
if ($_POST["elegido"]=="Valle del Cauca") {
    $options= '
    <option value="Cali"> Cali </option>
    <option value="Alcala"> Alcala </option>
    <option value="Andalucia"> Andalucia </option>
    <option value="Ansermanuevo"> Ansermanuevo </option>
    <option value="Argelia"> Argelia </option>
    <option value="Bolivar"> Bolivar </option>
    <option value="Buenaventura"> Buenaventura </option>
    <option value="Guadalajara de Buga"> Guadalajara de Buga </option>
    <option value="Bugalagrande"> Bugalagrande </option>
    <option value="Caicedonia"> Caicedonia </option>
    <option value="Calima"> Calima </option>
    <option value="Candelaria"> Candelaria </option>
    <option value="Cartago"> Cartago </option>
    <option value="Dagua"> Dagua </option>
    <option value="El Aguila"> El Aguila </option>
    <option value="El Cairo"> El Cairo </option>
    <option value="El Cerrito"> El Cerrito </option>
    <option value="El Dovio"> El Dovio </option>
    <option value="Florida"> Florida </option>
    <option value="Ginebra"> Ginebra </option>
    <option value="Guacari"> Guacari </option>
    <option value="Jamundi"> Jamundi </option>
    <option value="La Cumbre"> La Cumbre </option>
    <option value="La Unión"> La Unión </option>
    <option value="La Victoria"> La Victoria </option>
    <option value="Obando"> Obando </option>
    <option value="Palmira"> Palmira </option>
    <option value="Pradera"> Pradera </option>
    <option value="Restrepo"> Restrepo </option>
    <option value="Riofrio"> Riofrio </option>
    <option value="Roldanillo"> Roldanillo </option>
    <option value="San Pedro"> San Pedro </option>
    <option value="Sevilla"> Sevilla </option>
    <option value="Toro"> Toro </option>
    <option value="Trujillo"> Trujillo </option>
    <option value="Tulua"> Tulua </option>
    <option value="Ulloa"> Ulloa </option>
    <option value="Versalles"> Versalles </option>
    <option value="Vijes"> Vijes </option>
    <option value="Yotoco"> Yotoco </option>
    <option value="Yumbo"> Yumbo </option>
    <option value="Zarzal"> Zarzal </option>
    ';
}
if ($_POST["elegido"]=="Vaupés") {
    $options= '
    <option value="Mitu"> Mitu </option>
    <option value="Carucu"> Carucu </option>
    <option value="Pacoa"> Pacoa </option>
    <option value="Taraira"> Taraira </option>
    <option value="Papanua"> Papanua </option>
    <option value="Yavarate"> Yavarate </option>
    ';
}
if ($_POST["elegido"]=="Vichada") {
    $options= '
    <option value="Puerto Carreño"> Puerto Carreño </option>
    <option value="La Primavera"> La Primavera </option>
    <option value="Santa Rosalia"> Santa Rosalia </option>
    <option value="Cumaribo"> Cumaribo </option>
    ';
}
echo $options;
?>
